apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.Deployment.name }}--svc"
spec:
  selector:
    app: {{ .Values.Deployment.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.Deployment.port }}
      targetPort: {{ .Values.Deployment.port }}
      nodePort: {{ .Values.Service.nodeport }}   
  type: NodePort